sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gopinathsugumar/react-web -f Dockerfile.dev .

script:
  - docker run -e CI=true gopinathsugumar/react-web npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'docker-react-env'
  bucket_name: 'elasticbeanstalk-us-east-2-069617235597'
  bucket_path : 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_KEY_VALUE
