sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gopinathsugumar/react-web -f Dockerfile.dev .

script:
  - docker run -e CI=true gopinathsugumar/react-web npm run test -- --coverage
